# Generated by Django 5.2 on 2025-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='mentors/avatars/'),
        ),
    ]
