# Generated by Django 5.2 on 2025-04-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
