# Generated by Django 5.2 on 2025-05-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('mentors', '0004_alter_mentor_options_mentor_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mentors.mentor', verbose_name='Instructor'),
        ),
    ]
