# Generated by Django 5.2 on 2025-04-08 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('seller', 'Seller'), ('superuser', 'Superuser'), ('buyer', 'Buyer')], default='buyer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone_number', 'Phone number')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Uzbekistan phone number starting with +998', regex='^\\+998\\d{9}$')]),
        ),
    ]
