# Generated by Django 5.2 on 2025-05-01 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_type', models.CharField(choices=[('uzcard', 'Uzcard'), ('humo', 'Humo'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('unionpay', 'UnionPay')], max_length=20, verbose_name='Karta turi')),
                ('card_number', models.CharField(max_length=16, verbose_name='Karta raqami')),
                ('expire_date', models.CharField(max_length=5, verbose_name='Amal qilish muddati')),
                ('card_holder', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy karta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi kartasi',
                'verbose_name_plural': 'Foydalanuvchi kartalari',
                'db_table': 'users_card',
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'card_number')},
            },
        ),
    ]
